#!/usr/bin/env python3
"""Update bundled NSE holiday data.

Workflow
--------
NSE publishes its annual trading holidays calendar each December. To
refresh the bundled JSON without scraping their site (fragile), the
recommended flow is:

    1. Download the official PDF/HTML from
       https://www.nseindia.com/resources/exchange-communication-holidays
    2. Extract just the equity-segment holiday dates into a CSV with
       a single column ``date`` (YYYY-MM-DD).
    3. Run::

           python scripts/update_nse_holidays.py 2027 path/to/2027.csv

       which produces ``src/papertrade_india/data/nse_holidays_2027.json``.

This keeps the data layer fully reviewable in PRs (a JSON diff vs the
CSV input) and never makes a live network call from CI.

Validation
----------
The script also runs ``NSECalendar`` against the produced file to verify:
- All dates parse.
- No date falls on a weekend (those are already non-trading).
- No date is in a different year than declared.

Exit codes
----------
0 — success, file written.
1 — validation failed (input has bad data).
2 — input file missing or malformed.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import date
from pathlib import Path

DATA_DIR = (
    Path(__file__).resolve().parents[1]
    / "src" / "papertrade_india" / "data"
)


def load_csv(csv_path: Path) -> list[date]:
    rows: list[date] = []
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None or "date" not in reader.fieldnames:
            raise SystemExit(f"CSV must have a 'date' column. got: {reader.fieldnames}")
        for row in reader:
            raw = (row.get("date") or "").strip()
            if not raw:
                continue
            try:
                rows.append(date.fromisoformat(raw))
            except ValueError as e:
                raise SystemExit(f"Bad date {raw!r}: {e}") from e
    if not rows:
        raise SystemExit("CSV produced no dates")
    return sorted(set(rows))


def validate(year: int, dates: list[date]) -> list[str]:
    errors: list[str] = []
    for d in dates:
        if d.year != year:
            errors.append(f"{d}: wrong year (expected {year})")
        if d.weekday() >= 5:
            errors.append(f"{d}: falls on a weekend")
    return errors


def write_json(year: int, dates: list[date], note: str | None) -> Path:
    out = DATA_DIR / f"nse_holidays_{year}.json"
    payload = {
        "year": year,
        "source": (
            "Generated by scripts/update_nse_holidays.py from CSV input. "
            "Verify against https://www.nseindia.com/ before relying."
        ),
        "last_updated": date.today().isoformat(),
        "note": note or "",
        "holidays": [d.isoformat() for d in dates],
    }
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2) + "\n")
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("year", type=int, help="Calendar year, e.g. 2027")
    ap.add_argument("csv_path", type=Path,
                    help="CSV with a 'date' column (YYYY-MM-DD)")
    ap.add_argument("--note", default=None,
                    help="Optional free-text note attached to the JSON")
    args = ap.parse_args(argv)

    if not args.csv_path.exists():
        print(f"error: {args.csv_path} does not exist", file=sys.stderr)
        return 2

    dates = load_csv(args.csv_path)
    errors = validate(args.year, dates)
    if errors:
        print("Validation failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    out = write_json(args.year, dates, args.note)

    # Smoke-load through the calendar so a bad JSON write fails loudly.
    sys.path.insert(0, str(out.parent.parent.parent.parent))  # papertrade-india/src
    from papertrade_india import NSECalendar  # noqa: E402

    cal = NSECalendar(holidays_dir=DATA_DIR)
    loaded = sum(1 for d in dates if cal.is_holiday(d))
    if loaded != len(dates):
        print(
            f"warning: only {loaded}/{len(dates)} dates round-tripped "
            f"through NSECalendar — check the JSON",
            file=sys.stderr,
        )
        return 1

    print(f"wrote {out} ({len(dates)} dates)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
